apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-configuration
spec:
  selector: # kubectl get po -n istio-system --show-labels
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"   # Domain name of the external website
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-webapp
  namespace: default
spec:
  hosts:  # which incoming host are we applying the proxy
    - "*" # Copy the value in the gateway hosts
  gateways: 
    - ingress-gateway-configuration
  http:
    - match: 
      - uri: # IF
          prefix: "/experimental"
      - uri: # OR
          prefix: "/canary"
      route: # THEN
      - destination:
          host: fleetman-webapp.default.svc.cluster.local
          subset: experimental
    - match: 
      - uri : 
          prefix: "/"
      route:
      - destination:
          host: fleetman-webapp.default.svc.cluster.local
          subset: original
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-webapp
  namespace: default
spec:
  host: fleetman-webapp.default.svc.cluster.local
  subsets:
    - labels:
        version: original
      name: original
    - labels:
        version: experimental
      name: experimental
